/**
 *
 * Register all const for action types
 *
 */
export const FETCH_CHATSTICKER_REQUEST = 'FETCH_CHATSTICKER_REQUEST'
export const FETCH_CHATSTICKER_SUCCESS = 'FETCH_CHATSTICKER_SUCCESS'
export const FETCH_CHATSTICKER_FAILURE = 'FETCH_CHATSTICKER_FAILURE'
